version: "3"
services: 
    backend:
        build: ./backend
        volumes: 
            - "./backend:/app:rw"
        ports: 
            - "8000:80"
    frontend:
        build: ./frontend
        volumes:
            - "./frontend:/app:rw"
        ports: 
            - "8001:80"